In [3]:
from google.colab import files
uploaded = files.upload()

Saving ref.txt to ref (1).txt
Saving data.txt to data.txt
Saving col.txt to col (1).txt

In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import MinMaxScaler

print("Libraries loaded successfully.")

Libraries loaded successfully.

In [11]:
!ls

'col (1).txt'   col.txt   data.txt  'ref (1).txt'   ref.txt   sample_data

In [12]:
# Load column names
with open("col.txt", "r") as f:
    columns = [line.strip() for line in f.readlines()]

print("Total columns:", len(columns))
print("First 10 columns:", columns[:10])

Total columns: 70
First 10 columns: ['Actual Time', 'Age', 'Community Building', 'Community Membership_Family', 'Community Membership_Hobbies', 'Community Membership_None', 'Community Membership_Other', 'Community Membership_Political', 'Community Membership_Professional', 'Community Membership_Religious']

In [17]:
rows = []

with open("data.txt", "r") as f:
    for line in f:
        # Split manually on whitespace
        values = line.strip().split()
        rows.append(values)

print("Total rows:", len(rows))
print("First row length:", len(rows[0]))
print("First row preview:", rows[0][:10])

Total rows: 10104
First row length: 72
First row preview: ['5', '41', '2', '0', '0', '1', '0', '0', '0', '0']

In [21]:
# Keep only correct rows
clean_rows = [row for row in rows if len(row) == 72]

print("Rows kept:", len(clean_rows))

Rows kept: 7390

In [22]:
data_full = pd.DataFrame(clean_rows)
data_full = data_full.apply(pd.to_numeric, errors="coerce")

print("Clean dataset shape:", data_full.shape)

Clean dataset shape: (7390, 72)

In [23]:
columns_extended = columns + ["Extra_1", "Extra_2"]

print("New column count:", len(columns_extended))

New column count: 72

In [24]:
data_full.columns = columns_extended

data_full.head()

,Actual Time,Age,Community Building,Community Membership_Family,Community Membership_Hobbies,Community Membership_None,Community Membership_Other,Community Membership_Political,Community Membership_Professional,Community Membership_Religious,...,Who Pays for Access_Don't Know,Who Pays for Access_Other,Who Pays for Access_Parents,Who Pays for Access_School,Who Pays for Access_Self,Who Pays for Access_Work,Willingness to Pay Fees,Years on Internet,Extra_1,Extra_2
0,5,41,2,0,0,1,0,0,0,0,...,1,0,0,0,0,1,0,99,2,93819
1,2,28,2,0,0,0,0,0,0,0,...,2,0,0,0,0,1,0,4,0,95708
2,99,25,0,1,1,0,0,0,1,0,...,1,0,0,0,0,1,1,99,2,97218
3,29,28,0,0,0,0,1,0,0,0,...,1,0,0,0,0,1,0,4,2,91627
4,15,17,0,0,0,0,0,1,1,0,...,1,0,0,0,0,1,0,4,2,49906

In [25]:
data_full[["Extra_1", "Extra_2"]].describe()

           Extra_1       Extra_2
count  7390.000000   7390.000000
mean      2.129229  92312.554398
std       1.037632  12212.441086
min       0.000000     42.000000
25%       2.000000  92125.250000
50%       2.000000  94742.500000
75%       3.000000  97286.250000
max       4.000000  99968.000000

In [26]:
selected_cols = [
    "Education",
    "Income",
    "Employment",
    "Household_Size",
    "Computer_Ownership",
    "Internet_Access",
    "Internet_Frequency",
    "Tech_Confidence",
    "Online_Activities",
    "Digital_Skill"
]

In [28]:
print(len(data_full.columns))
print(data_full.columns[:20])

72
Index(['Actual Time', 'Age', 'Community Building',
       'Community Membership_Family', 'Community Membership_Hobbies',
       'Community Membership_None', 'Community Membership_Other',
       'Community Membership_Political', 'Community Membership_Professional',
       'Community Membership_Religious', 'Community Membership_Support',
       'Country\tDisability_Cognitive', 'Disability_Hearing',
       'Disability_Motor', 'Disability_Not Impaired', 'Disability_Not Say',
       'Disability_Vision', 'Education Attainment',
       'Falsification of Information', 'Gender'],
      dtype='object')

In [29]:
for col in data_full.columns:
    print(col)

Actual Time
Age
Community Building
Community Membership_Family
Community Membership_Hobbies
Community Membership_None
Community Membership_Other
Community Membership_Political
Community Membership_Professional
Community Membership_Religious
Community Membership_Support
Country	Disability_Cognitive
Disability_Hearing
Disability_Motor
Disability_Not Impaired
Disability_Not Say
Disability_Vision
Education Attainment
Falsification of Information
Gender
Household Income
How You Heard About Survey_Banner
How You Heard About Survey_Friend
How You Heard About Survey_Mailing List
How You Heard About Survey_Others
How You Heard About Survey_Printed Media
How You Heard About Survey_Remebered
How You Heard About Survey_Search Engine
How You Heard About Survey_Usenet News
How You Heard About Survey_WWW Page
Major Geographical Location
Major Occupation
Marital Status
Most Import Issue Facing the Internet
Opinions on Censorship
Primary Computing Platform
Primary Language
Primary Place of WWW Access
Race
Not Purchasing_Bad experience
Not Purchasing_Bad press
Not Purchasing_Cant find
Not Purchasing_Company policy
Not Purchasing_Easier locally
Not Purchasing_Enough info
Not Purchasing_Judge quality
Not Purchasing_Never tried
Not Purchasing_No credit
Not Purchasing_Not applicable
Not Purchasing_Not option
Not Purchasing_Other
Not Purchasing_Prefer people
Not Purchasing_Privacy
Not Purchasing_Receipt
Not Purchasing_Security
Not Purchasing_Too complicated
Not Purchasing_Uncomfortable
Not Purchasing_Unfamiliar vendor
Registered to Vote
Sexual Preference
Web Ordering
Web Page Creation
Who Pays for Access_Don't Know
Who Pays for Access_Other
Who Pays for Access_Parents
Who Pays for Access_School
Who Pays for Access_Self
Who Pays for Access_Work
Willingness to Pay Fees
Years on Internet
Extra_1
Extra_2

In [30]:
selected_cols = [
    "Age",
    "Education Attainment",
    "Household Income",
    "Major Occupation",
    "Years on Internet",
    "Web Ordering",
    "Web Page Creation",
    "Willingness to Pay Fees",
    "Primary Place of WWW Access",
    "Who Pays for Access_Self",
    "Who Pays for Access_Work",
    "Community Building"
]

data_full[selected_cols].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7390 entries, 0 to 7389
Data columns (total 12 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Age                          7390 non-null   int64
 1   Education Attainment         7390 non-null   int64
 2   Household Income             7390 non-null   int64
 3   Major Occupation             7390 non-null   int64
 4   Years on Internet            7390 non-null   int64
 5   Web Ordering                 7390 non-null   int64
 6   Web Page Creation            7390 non-null   int64
 7   Willingness to Pay Fees      7390 non-null   int64
 8   Primary Place of WWW Access  7390 non-null   int64
 9   Who Pays for Access_Self     7390 non-null   int64
 10  Who Pays for Access_Work     7390 non-null   int64
 11  Community Building           7390 non-null   int64
dtypes: int64(12)
memory usage: 692.9 KB

In [31]:
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

X = data_full[selected_cols]

# Standardize
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# PCA
pca = PCA()
X_pca = pca.fit_transform(X_scaled)

# Explained variance
print("Explained variance ratio:")
print(pca.explained_variance_ratio_)

# Use PC1 as index
data_full["Digital_Readiness_Index"] = X_pca[:, 0]

data_full[["Digital_Readiness_Index"]].head()

Explained variance ratio:
[0.14376454 0.10698271 0.09110964 0.08896804 0.08496461 0.08363105
 0.08090706 0.08068385 0.07487941 0.0708169  0.05600929 0.03728291]

   Digital_Readiness_Index
0                 1.130316
1                 0.541887
2                 0.414632
3                 0.545147
4                 0.455325

In [32]:
import numpy as np

cumulative_variance = np.cumsum(pca.explained_variance_ratio_)
print(cumulative_variance)

[0.14376454 0.25074725 0.34185689 0.43082493 0.51578953 0.59942058
 0.68032764 0.76101149 0.8358909  0.9067078  0.96271709 1.        ]

In [33]:
import numpy as np

# Number of components to use
k = 6

# Get first 6 components
components = X_pca[:, :k]

# Get their explained variance ratios
weights = pca.explained_variance_ratio_[:k]

# Normalize weights (optional but cleaner)
weights = weights / weights.sum()

# Construct weighted index
digital_index = np.dot(components, weights)

# Add to dataframe
data_full["Digital_Readiness_Index"] = digital_index

data_full["Digital_Readiness_Index"].describe()

count    7.390000e+03
mean    -2.163357e-18
std      4.784974e-01
min     -1.445106e+00
25%     -2.831168e-01
50%      6.485608e-02
75%      3.109579e-01
max      3.840421e+00
Name: Digital_Readiness_Index, dtype: float64

In [34]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
data_full["Digital_Readiness_Index"] = scaler.fit_transform(
    data_full[["Digital_Readiness_Index"]]
) * 100

data_full["Digital_Readiness_Index"].describe()

count    7390.000000
mean       27.340814
std         9.052973
min         0.000000
25%        21.984361
50%        28.567864
75%        33.224010
max       100.000000
Name: Digital_Readiness_Index, dtype: float64